blank_issues_enabled: false
contact_links:
  - name: "Cổng Thông tin Eternal Flame Tech"
    url: "https://eft.io.vn"
    about: "Trang chủ chính thức của Câu lạc bộ AI & Robotics THPT Chuyên Nguyễn Thị Minh Khai, Cần Thơ."
